export const FETCH_GROUP_LOCKS_START = 'FETCH_GROUP_LOCKS_START';
export const FETCH_GROUP_LOCKS_SUCCESS = 'FETCH_GROUP_LOCKS_SUCCESS';
export const FETCH_GROUP_LOCKS_FAIL = 'FETCH_GROUP_LOCKS_FAIL';

export const ASSIGN_LOCK_START = 'ASSIGN_LOCK_START';
export const ASSIGN_LOCK_SUCCESS = 'ASSIGN_LOCK_SUCCESS';
export const ASSIGN_LOCK_FAIL = 'ASSIGN_LOCK_FAIL';
export const UNASSIGN_LOCK_START = 'UNASSIGN_LOCK_START';
export const UNASSIGN_LOCK_SUCCESS = 'UNASSIGN_LOCK_SUCCESS';
export const UNASSIGN_LOCK_FAIL = 'UNASSIGN_LOCK_FAIL';
export const UNASSIGN_ALL_LOCK_START = 'UNASSIGN_ALL_LOCK_START';
export const UNASSIGN_ALL_LOCK_SUCCESS = 'UNASSIGN_ALL_LOCK_SUCCESS';
export const UNASSIGN_ALL_LOCK_FAIL = 'UNASSIGN_ALL_LOCK_FAIL';